apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: c01
          image: vivekkallate/staragilehealthcareproject:v1
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort  # or NodePort for local testing
